"""API错误码定义

后端返回error_code而非中文detail，前端根据error_code映射i18n文本。
格式: ERR_{模块}_{错误类型}

FIXED: 原问题-后端API错误消息中文硬编码，无法国际化且前端依赖字符串匹配
"""


class AuthErrors:
    RATE_LIMITED = "ERR_AUTH_RATE_LIMITED"
    INVALID_CREDENTIALS = "ERR_AUTH_INVALID_CREDENTIALS"
    USER_DISABLED = "ERR_AUTH_USER_DISABLED"
    LOGIN_FAILED = "ERR_AUTH_LOGIN_FAILED"
    REFRESH_TOKEN_INVALID = "ERR_AUTH_REFRESH_TOKEN_INVALID"
    USER_NOT_FOUND = "ERR_AUTH_USER_NOT_FOUND"
    OLD_PASSWORD_WRONG = "ERR_AUTH_OLD_PASSWORD_WRONG"
    PASSWORD_POLICY = "ERR_AUTH_PASSWORD_POLICY"
    PASSWORD_TOO_LONG = "ERR_AUTH_PASSWORD_TOO_LONG"
    PASSWORD_SAME_AS_OLD = "ERR_AUTH_PASSWORD_SAME_AS_OLD"
    PASSWORD_LETTER_AND_DIGIT = "ERR_AUTH_PASSWORD_LETTER_AND_DIGIT"
    PASSWORD_CHANGE_FAILED = "ERR_AUTH_PASSWORD_CHANGE_FAILED"
    TOKEN_INVALID = "ERR_AUTH_TOKEN_INVALID"
    TOKEN_REVOKED = "ERR_AUTH_TOKEN_REVOKED"
    LOGOUT_FAILED = "ERR_AUTH_LOGOUT_FAILED"


class UserErrors:
    LIST_FAILED = "ERR_USER_LIST_FAILED"
    USERNAME_EXISTS = "ERR_USER_USERNAME_EXISTS"
    CREATE_FAILED = "ERR_USER_CREATE_FAILED"
    CANNOT_REMOVE_LAST_ADMIN = "ERR_USER_CANNOT_REMOVE_LAST_ADMIN"
    USER_NOT_FOUND = "ERR_USER_USER_NOT_FOUND"
    UPDATE_FAILED = "ERR_USER_UPDATE_FAILED"
    CANNOT_DELETE_SELF = "ERR_USER_CANNOT_DELETE_SELF"
    CANNOT_DELETE_ADMIN = "ERR_USER_CANNOT_DELETE_ADMIN"
    CANNOT_DELETE_LAST_ADMIN = "ERR_USER_CANNOT_DELETE_LAST_ADMIN"
    DELETE_FAILED = "ERR_USER_DELETE_FAILED"


class ServiceErrors:
    LIST_FAILED = "ERR_SVC_LIST_FAILED"
    UNKNOWN_SERVICE = "ERR_SVC_UNKNOWN_SERVICE"
    NOT_REGISTERED = "ERR_SVC_NOT_REGISTERED"
    STATUS_FAILED = "ERR_SVC_STATUS_FAILED"
    ENABLE_FAILED = "ERR_SVC_ENABLE_FAILED"
    DISABLE_FAILED = "ERR_SVC_DISABLE_FAILED"
    START_FAILED = "ERR_SVC_START_FAILED"
    STOP_FAILED = "ERR_SVC_STOP_FAILED"
    INSTALL_FAILED = "ERR_SVC_INSTALL_FAILED"
    CONFIG_UPDATE_FAILED = "ERR_SVC_CONFIG_UPDATE_FAILED"
    DEPS_INSTALL_FAILED = "ERR_SVC_DEPS_INSTALL_FAILED"
    SERIAL_PORT_UNAVAILABLE = "ERR_SVC_SERIAL_PORT_UNAVAILABLE"


class DeviceErrors:
    NOT_FOUND = "ERR_DEVICE_NOT_FOUND"
    PUSH_EMPTY = "ERR_DEVICE_PUSH_EMPTY"
    PUSH_INVALID_ID = "ERR_DEVICE_PUSH_INVALID_ID"
    PUSH_INVALID_KEY = "ERR_DEVICE_PUSH_INVALID_KEY"  # FIXED: 原问题-push_data无key校验
    WEBHOOK_AUTH_FAILED = "ERR_DEVICE_WEBHOOK_AUTH_FAILED"
    PUSH_FAILED = "ERR_DEVICE_PUSH_FAILED"
    LIST_FAILED = "ERR_DEVICE_LIST_FAILED"
    CREATE_FAILED = "ERR_DEVICE_CREATE_FAILED"
    GET_FAILED = "ERR_DEVICE_GET_FAILED"
    UPDATE_FAILED = "ERR_DEVICE_UPDATE_FAILED"
    DELETE_FAILED = "ERR_DEVICE_DELETE_FAILED"
    POINTS_FAILED = "ERR_DEVICE_POINTS_FAILED"
    WRITE_FAILED = "ERR_DEVICE_WRITE_FAILED"
    API_KEY_INVALID = "ERR_DEVICE_API_KEY_INVALID"
    API_KEY_NOT_CONFIGURED = "ERR_DEVICE_API_KEY_NOT_CONFIGURED"
    SIMULATOR_FAILED = "ERR_DEVICE_SIMULATOR_FAILED"
    DISCOVER_FAILED = "ERR_DEVICE_DISCOVER_FAILED"
    PUSH_DRIVER_NOT_READY = "ERR_DEVICE_PUSH_DRIVER_NOT_READY"


class PreprocessErrors:
    GET_FAILED = "ERR_PREPROCESS_GET_FAILED"
    NOT_INITIALIZED = "ERR_PREPROCESS_NOT_INITIALIZED"
    UPDATE_FAILED = "ERR_PREPROCESS_UPDATE_FAILED"


class CommonErrors:
    SERVICE_NOT_READY = "ERR_COMMON_SERVICE_NOT_READY"
    DB_NOT_READY = "ERR_COMMON_DB_NOT_READY"
    INTERNAL_ERROR = "ERR_COMMON_INTERNAL_ERROR"
    NOT_FOUND = "ERR_COMMON_NOT_FOUND"


class RepoErrors:
    DEVICE_EXISTS = "ERR_REPO_DEVICE_EXISTS"
    RULE_EXISTS = "ERR_REPO_RULE_EXISTS"
    ALARM_EXISTS = "ERR_REPO_ALARM_EXISTS"
    USERNAME_EXISTS = "ERR_REPO_USERNAME_EXISTS"
    DB_MODE_SESSION_REQUIRED = "ERR_REPO_DB_MODE_SESSION_REQUIRED"
    NO_SESSION_AVAILABLE = "ERR_REPO_NO_SESSION_AVAILABLE"


class DatabaseErrors:
    UNSUPPORTED_BACKEND = "ERR_DB_UNSUPPORTED_BACKEND"
    DRIVER_REQUIRED = "ERR_DB_DRIVER_REQUIRED"
    NOT_CONNECTED = "ERR_DB_NOT_CONNECTED"
    SESSION_NOT_INIT = "ERR_DB_SESSION_NOT_INIT"


class ConfigErrors:
    LOAD_FAILED = "ERR_CONFIG_LOAD_FAILED"
    SAVE_FAILED = "ERR_CONFIG_SAVE_FAILED"


class DriverErrors:
    START_FAILED = "ERR_DRIVER_START_FAILED"
    NOT_FOUND = "ERR_DRIVER_NOT_FOUND"
    REGISTRY_NOT_INIT = "ERR_DRIVER_REGISTRY_NOT_INIT"
    LIST_FAILED = "ERR_DRIVER_LIST_FAILED"
    GET_FAILED = "ERR_DRIVER_GET_FAILED"
    DISCOVER_FAILED = "ERR_DRIVER_DISCOVER_FAILED"


class DataErrors:
    UNSUPPORTED_AGGREGATE = "ERR_DATA_UNSUPPORTED_AGGREGATE"
    QUERY_FAILED = "ERR_DATA_QUERY_FAILED"
    EXPORT_FAILED = "ERR_DATA_EXPORT_FAILED"


class VideoErrors:
    PTZ_FAILED = "ERR_VIDEO_PTZ_FAILED"
    WEBHOOK_FAILED = "ERR_VIDEO_WEBHOOK_FAILED"
    API_KEY_INVALID = "ERR_VIDEO_API_KEY_INVALID"
    API_KEY_NOT_CONFIGURED = "ERR_VIDEO_API_KEY_NOT_CONFIGURED"


class AuditErrors:
    INVALID_ACTION = "ERR_AUDIT_INVALID_ACTION"
    INVALID_TIME_FORMAT = "ERR_AUDIT_INVALID_TIME_FORMAT"
    NOT_ENABLED = "ERR_AUDIT_NOT_ENABLED"
    CLEANUP_FAILED = "ERR_AUDIT_CLEANUP_FAILED"
    EXPORT_FAILED = "ERR_AUDIT_EXPORT_FAILED"
    INTEGRITY_FAILED = "ERR_AUDIT_INTEGRITY_FAILED"
    LIST_FAILED = "ERR_AUDIT_LIST_FAILED"


class ExpressionErrors:
    EVALUATE_FAILED = "ERR_EXPR_EVALUATE_FAILED"
    BATCH_EVALUATE_FAILED = "ERR_EXPR_BATCH_EVALUATE_FAILED"
    VALIDATE_FAILED = "ERR_EXPR_VALIDATE_FAILED"


class ScadaErrors:
    PROJECT_NOT_FOUND = "ERR_SCADA_PROJECT_NOT_FOUND"
    SAVE_FAILED = "ERR_SCADA_SAVE_FAILED"
    DELETE_FAILED = "ERR_SCADA_DELETE_FAILED"
    LOAD_FAILED = "ERR_SCADA_LOAD_FAILED"


class PlatformErrors:
    CONFIG_SCHEMA_NOT_FOUND = "ERR_PLATFORM_CONFIG_SCHEMA_NOT_FOUND"
    CONNECT_FAILED = "ERR_PLATFORM_CONNECT_FAILED"
    DISCONNECT_FAILED = "ERR_PLATFORM_DISCONNECT_FAILED"
    NOT_SUPPORTED = "ERR_PLATFORM_NOT_SUPPORTED"
    MISSING_CONFIG = "ERR_PLATFORM_MISSING_CONFIG"
    NOT_CONNECTED = "ERR_PLATFORM_NOT_CONNECTED"


class SystemErrors:
    STATUS_FAILED = "ERR_SYS_STATUS_FAILED"
    BACKUP_LIST_FAILED = "ERR_SYS_BACKUP_LIST_FAILED"
    BACKUP_CREATE_FAILED = "ERR_SYS_BACKUP_CREATE_FAILED"
    INVALID_BACKUP_ID = "ERR_SYS_INVALID_BACKUP_ID"
    BACKUP_NOT_FOUND = "ERR_SYS_BACKUP_NOT_FOUND"
    RESTORE_FAILED = "ERR_SYS_RESTORE_FAILED"


class RuleErrors:
    LIST_FAILED = "ERR_RULE_LIST_FAILED"
    CREATE_FAILED = "ERR_RULE_CREATE_FAILED"
    NOT_FOUND = "ERR_RULE_NOT_FOUND"
    GET_FAILED = "ERR_RULE_GET_FAILED"
    UPDATE_FAILED = "ERR_RULE_UPDATE_FAILED"
    DELETE_FAILED = "ERR_RULE_DELETE_FAILED"
    ENABLE_FAILED = "ERR_RULE_ENABLE_FAILED"
    DISABLE_FAILED = "ERR_RULE_DISABLE_FAILED"
    TEST_FAILED = "ERR_RULE_TEST_FAILED"


class AlarmErrors:
    LIST_FAILED = "ERR_ALARM_LIST_FAILED"
    NOT_FOUND = "ERR_ALARM_NOT_FOUND"
    GET_FAILED = "ERR_ALARM_GET_FAILED"
    ACK_FAILED = "ERR_ALARM_ACK_FAILED"


class IntegrationErrors:
    HANDSHAKE_FAILED = "ERR_INTEG_HANDSHAKE_FAILED"
    STATUS_FAILED = "ERR_INTEG_STATUS_FAILED"


class McpErrors:
    DEVICE_SERVICE_UNAVAILABLE = "ERR_MCP_DEVICE_SERVICE_UNAVAILABLE"
    MISSING_DEVICE_ID = "ERR_MCP_MISSING_DEVICE_ID"
    DEVICE_NOT_FOUND = "ERR_MCP_DEVICE_NOT_FOUND"
    MISSING_PARAMS = "ERR_MCP_MISSING_PARAMS"
    ALARM_SERVICE_UNAVAILABLE = "ERR_MCP_ALARM_SERVICE_UNAVAILABLE"
    SYSTEM_SERVICE_UNAVAILABLE = "ERR_MCP_SYSTEM_SERVICE_UNAVAILABLE"
    RULE_SERVICE_UNAVAILABLE = "ERR_MCP_RULE_SERVICE_UNAVAILABLE"
    UNKNOWN_TOOL = "ERR_MCP_UNKNOWN_TOOL"
    LIST_FAILED = "ERR_MCP_LIST_FAILED"
    CALL_FAILED = "ERR_MCP_CALL_FAILED"
    CREATE_KEY_FAILED = "ERR_MCP_CREATE_KEY_FAILED"
    KEY_NOT_FOUND = "ERR_MCP_KEY_NOT_FOUND"
    SSE_FAILED = "ERR_MCP_SSE_FAILED"


class OtaErrors:
    NOT_ENABLED = "ERR_OTA_NOT_ENABLED"
    CHECK_FAILED = "ERR_OTA_CHECK_FAILED"
    IN_PROGRESS = "ERR_OTA_IN_PROGRESS"
    NO_UPDATE = "ERR_OTA_NO_UPDATE"
    NO_DOWNLOAD_URL = "ERR_OTA_NO_DOWNLOAD_URL"
    DOWNLOAD_FAILED = "ERR_OTA_DOWNLOAD_FAILED"
    APPLY_FAILED = "ERR_OTA_APPLY_FAILED"
    ROLLBACK_FAILED = "ERR_OTA_ROLLBACK_FAILED"
    LIST_BACKUPS_FAILED = "ERR_OTA_LIST_BACKUPS_FAILED"


class AuthzErrors:
    NOT_AUTHENTICATED = "ERR_AUTHZ_NOT_AUTHENTICATED"
    PERMISSION_DENIED = "ERR_AUTHZ_PERMISSION_DENIED"


class GrafanaErrors:
    NOT_ENABLED = "ERR_GRAFANA_NOT_ENABLED"
    API_KEY_MISSING = "ERR_GRAFANA_API_KEY_MISSING"
    BAD_STATUS = "ERR_GRAFANA_BAD_STATUS"
    DEPS_MISSING = "ERR_GRAFANA_DEPS_MISSING"
    CONNECTION_FAILED = "ERR_GRAFANA_CONNECTION_FAILED"
    INVALID_UID = "ERR_GRAFANA_INVALID_UID"
