"""API错误码定义

后端返回error_code而非中文detail，前端根据error_code映射i18n文本。
格式: ERR_{模块}_{错误类型}

FIXED: 原问题-后端API错误消息中文硬编码，无法国际化且前端依赖字符串匹配
"""


class AuthErrors:
    RATE_LIMITED = "ERR_AUTH_RATE_LIMITED"
    INVALID_CREDENTIALS = "ERR_AUTH_INVALID_CREDENTIALS"
    USER_DISABLED = "ERR_AUTH_USER_DISABLED"
    LOGIN_FAILED = "ERR_AUTH_LOGIN_FAILED"
    REFRESH_TOKEN_INVALID = "ERR_AUTH_REFRESH_TOKEN_INVALID"
    USER_NOT_FOUND = "ERR_AUTH_USER_NOT_FOUND"
    OLD_PASSWORD_WRONG = "ERR_AUTH_OLD_PASSWORD_WRONG"
    PASSWORD_POLICY = "ERR_AUTH_PASSWORD_POLICY"
    PASSWORD_TOO_LONG = "ERR_AUTH_PASSWORD_TOO_LONG"
    PASSWORD_SAME_AS_OLD = "ERR_AUTH_PASSWORD_SAME_AS_OLD"
    PASSWORD_LETTER_AND_DIGIT = "ERR_AUTH_PASSWORD_LETTER_AND_DIGIT"
    PASSWORD_CHANGE_FAILED = "ERR_AUTH_PASSWORD_CHANGE_FAILED"
    TOKEN_INVALID = "ERR_AUTH_TOKEN_INVALID"
    TOKEN_REVOKED = "ERR_AUTH_TOKEN_REVOKED"
    LOGOUT_FAILED = "ERR_AUTH_LOGOUT_FAILED"


class UserErrors:
    LIST_FAILED = "ERR_USER_LIST_FAILED"
    USERNAME_EXISTS = "ERR_USER_USERNAME_EXISTS"
    CREATE_FAILED = "ERR_USER_CREATE_FAILED"
    CANNOT_REMOVE_LAST_ADMIN = "ERR_USER_CANNOT_REMOVE_LAST_ADMIN"
    USER_NOT_FOUND = "ERR_USER_USER_NOT_FOUND"
    UPDATE_FAILED = "ERR_USER_UPDATE_FAILED"
    CANNOT_DELETE_SELF = "ERR_USER_CANNOT_DELETE_SELF"
    CANNOT_DELETE_LAST_ADMIN = "ERR_USER_CANNOT_DELETE_LAST_ADMIN"
    DELETE_FAILED = "ERR_USER_DELETE_FAILED"


class ServiceErrors:
    LIST_FAILED = "ERR_SVC_LIST_FAILED"
    UNKNOWN_SERVICE = "ERR_SVC_UNKNOWN_SERVICE"
    NOT_REGISTERED = "ERR_SVC_NOT_REGISTERED"
    STATUS_FAILED = "ERR_SVC_STATUS_FAILED"
    ENABLE_FAILED = "ERR_SVC_ENABLE_FAILED"
    DISABLE_FAILED = "ERR_SVC_DISABLE_FAILED"
    START_FAILED = "ERR_SVC_START_FAILED"
    STOP_FAILED = "ERR_SVC_STOP_FAILED"
    INSTALL_FAILED = "ERR_SVC_INSTALL_FAILED"
    CONFIG_UPDATE_FAILED = "ERR_SVC_CONFIG_UPDATE_FAILED"
    DEPS_INSTALL_FAILED = "ERR_SVC_DEPS_INSTALL_FAILED"
    SERIAL_PORT_UNAVAILABLE = "ERR_SVC_SERIAL_PORT_UNAVAILABLE"


class DeviceErrors:
    NOT_FOUND = "ERR_DEVICE_NOT_FOUND"
    PUSH_EMPTY = "ERR_DEVICE_PUSH_EMPTY"
    PUSH_INVALID_ID = "ERR_DEVICE_PUSH_INVALID_ID"
    WEBHOOK_AUTH_FAILED = "ERR_DEVICE_WEBHOOK_AUTH_FAILED"
    PUSH_FAILED = "ERR_DEVICE_PUSH_FAILED"
    LIST_FAILED = "ERR_DEVICE_LIST_FAILED"
    CREATE_FAILED = "ERR_DEVICE_CREATE_FAILED"
    GET_FAILED = "ERR_DEVICE_GET_FAILED"
    UPDATE_FAILED = "ERR_DEVICE_UPDATE_FAILED"
    DELETE_FAILED = "ERR_DEVICE_DELETE_FAILED"
    POINTS_FAILED = "ERR_DEVICE_POINTS_FAILED"
    WRITE_FAILED = "ERR_DEVICE_WRITE_FAILED"
    SIMULATOR_FAILED = "ERR_DEVICE_SIMULATOR_FAILED"
    DISCOVER_FAILED = "ERR_DEVICE_DISCOVER_FAILED"
    PUSH_DRIVER_NOT_READY = "ERR_DEVICE_PUSH_DRIVER_NOT_READY"


class PreprocessErrors:
    GET_FAILED = "ERR_PREPROCESS_GET_FAILED"
    NOT_INITIALIZED = "ERR_PREPROCESS_NOT_INITIALIZED"
    UPDATE_FAILED = "ERR_PREPROCESS_UPDATE_FAILED"


class CommonErrors:
    SERVICE_NOT_READY = "ERR_COMMON_SERVICE_NOT_READY"
    DB_NOT_READY = "ERR_COMMON_DB_NOT_READY"
    INTERNAL_ERROR = "ERR_COMMON_INTERNAL_ERROR"
    NOT_FOUND = "ERR_COMMON_NOT_FOUND"


class RepoErrors:
    DEVICE_EXISTS = "ERR_REPO_DEVICE_EXISTS"
    RULE_EXISTS = "ERR_REPO_RULE_EXISTS"
    ALARM_EXISTS = "ERR_REPO_ALARM_EXISTS"
    USERNAME_EXISTS = "ERR_REPO_USERNAME_EXISTS"
    DB_MODE_SESSION_REQUIRED = "ERR_REPO_DB_MODE_SESSION_REQUIRED"
    NO_SESSION_AVAILABLE = "ERR_REPO_NO_SESSION_AVAILABLE"


class DatabaseErrors:
    UNSUPPORTED_BACKEND = "ERR_DB_UNSUPPORTED_BACKEND"
    DRIVER_REQUIRED = "ERR_DB_DRIVER_REQUIRED"
    NOT_CONNECTED = "ERR_DB_NOT_CONNECTED"
    SESSION_NOT_INIT = "ERR_DB_SESSION_NOT_INIT"


class ConfigErrors:
    LOAD_FAILED = "ERR_CONFIG_LOAD_FAILED"
    SAVE_FAILED = "ERR_CONFIG_SAVE_FAILED"


class DriverErrors:
    START_FAILED = "ERR_DRIVER_START_FAILED"
