{{- if .Values.edgelite.security.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edgelite.fullname" . }}
  labels:
    {{- include "edgelite.labels" . | nindent 4 }}
type: Opaque
stringData:
  EDGELITE_SECURITY__SECRET_KEY: {{ .Values.edgelite.security.secretKey | quote }}
  EDGELITE_ADMIN_PASSWORD: {{ .Values.edgelite.adminPassword | quote }}
  EDGELITE_INFLUXDB__TOKEN: {{ .Values.edgelite.influxdb.token | quote }}
  EDGELITE_MQTT__PASSWORD: {{ .Values.edgelite.mqtt.password | quote }}
  {{- if .Values.edgelite.influxdb.password }}
  EDGELITE_INFLUXDB__PASSWORD: {{ .Values.edgelite.influxdb.password | quote }}
  {{- end }}
{{- end }}
