# Minimal type stubs for asyncua to satisfy pyright
# asyncua doesn't include type stubs, so we provide minimal ones

from typing import Any, Coroutine, Sequence

class Client:
    """Minimal Client stub for asyncua."""
    url: str
    session_timeout: float
    security_mode: Any
    security_policy: Any
    
    def __init__(self, url: str) -> None: ...
    
    async def connect(self) -> None: ...
    
    async def disconnect(self) -> None: ...
    
    async def get_root_node(self) -> "Node": ...
    
    async def get_objects_node(self) -> "Node": ...
    
    async def get_node(self, nodeid: Any) -> "Node": ...
    
    def set_user(self, user: str) -> None: ...
    
    def set_password(self, password: str) -> None: ...
    
    def set_security(self, *args: Any, **kwargs: Any) -> None: ...
    
    async def create_subscription(self, *args: Any, **kwargs: Any) -> "Subscription": ...

class Node:
    """Minimal Node stub for asyncua."""
    nodeid: Any
    
    def __init__(self, nodeid: Any) -> None: ...
    
    async def get_child(self, *args: Any, **kwargs: Any) -> "Node": ...
    
    async def read_value(self) -> Any: ...
    
    async def write_value(self, value: Any) -> None: ...
    
    async def call_method(self, *args: Any, **kwargs: Any) -> Any: ...
    
    def get_browse_name(self) -> Any: ...
    
    def get_display_name(self) -> Any: ...
    
    async def read_attribute(self, *args: Any, **kwargs: Any) -> Any: ...

class Subscription:
    """Minimal Subscription stub for asyncua."""
    
    def __init__(self) -> None: ...
    
    async def delete(self) -> None: ...
    
    async def subscribe_data_change(self, *args: Any, **kwargs: Any) -> "MonitoredItem": ...

class MonitoredItem:
    """Minimal MonitoredItem stub for asyncua."""
    
    def __init__(self) -> None: ...

# Common types and constants from asyncua
ua: Any